const Routes = {
  Welcome: '/welcome',
  CreatePassword: '/password',
  NoAddress: '/no-address',
  StartChainManagement: '/start-chain-management',
  CreateMnemonics: '/create-mnemonics',
  ScreenSuccess: '/screen-success',
  ScreenFailed: '/screen-failed',
  Redirect: '/screen-redirect',
  ImportPrivateKey: '/import/key',
  ImportJson: '/import/json',
  ImportMnemonics: '/import/mnemonics',
  ImportAccount: '/import/account',
  ImportQRCode: '/import/qr-code',
  ImportURL: '/import/url',
  AddCustomNetwork: '/add-custom-network',
  AddNetwork: '/add-network',
  AddChainlistNetwork: '/add-chainlist-network',
  Dashboard: '/dashboard',
  BuyToken: '/buy-token',
  SendToken: '/send-token',
  Santa: '/santa',
  Swap: '/swap',
  SearchToken: '/search-token',
  AddCustomToken: '/add-custom-token',
  SettingBoard: '/setting-board',
  Unlock: '/unlock',
  GeneralSetting: '/general-setting',
  AdvancedSetting: '/advanced-setting',
  ContactsSetting: '/contacts-setting',
  NetworksSetting: '/networks-setting',
  PrivateInfoSetting: '/private-info-setting',
  CommingSoon: '/comming-soon',
};
export default Routes;
