const VERIFY_ACTIONS = {
  RETRIEVE: 'RETRIEVE',
  EMAIL: 'EMAIL',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  CODE: 'CODE',
  VERIFY_CODE: 'VERIFY_CODE',
  ERROR: 'ERROR',
};

export default VERIFY_ACTIONS;
